version: '3.8'

services:
  db:
    container_name: test-db
    build:
      context: ./test-db
    ports:
      - '23306:3306'
    volumes:
      - test-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo

volumes:
  test-db-data: