CREATE DATABASE IF NOT EXISTS `app`;

CREATE USER 'app'@'%' IDENTIFIED BY 'app';

GRANT ALL ON `app`.* TO 'app'@'%';

-- Flywayが起動時に「performance_schema.user_variables_by_thread 」を参照しようとしてエラーになるので、SELECT権限を付与する。
GRANT SELECT ON performance_schema.user_variables_by_thread TO 'app'@'%';


-- テーブルが重複しないよう存在チェック、あれば削除します
use app;
DROP TABLE IF EXISTS MEMBER;
DROP TABLE IF EXISTS TEAM;

-- テーブル
CREATE TABLE TEAM (
  TEAM_ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  TYPE VARCHAR(20) NOT NULL,
  VERSION INT NOT NULL,
  PRIMARY KEY (TEAM_ID)
);

CREATE TABLE MEMBER (
  MEMBER_ID BIGINT NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  VERSION INT NOT NULL,
  TEAM_ID BIGINT NOT NULL,
  PRIMARY KEY (MEMBER_ID)
);

ALTER TABLE MEMBER
	ADD CONSTRAINT FK_MEMBER_TEAM FOREIGN KEY (TEAM_ID)
	REFERENCES TEAM (TEAM_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;